---
- name: Copy clients config file
  template:
    src: '{{ item }}'
    dest: '/etc/openvpn/{{ openvpn_config_name }}.conf'
  with_items:
    - etc/openvpn/{{ openvpn_config_name}}.conf.j2
  notify: restart openvpn
