---
- name: Copy clients config file
  template:
    src: '{{ item }}'
    dest: '{{ openvpn_config_dir }}/{{ openvpn_config_name }}'
  with_items:
    - etc/openvpn/{{ openvpn_config_name}}.j2
  notify: restart openvpn

- name: Enable and start openvpn service
  systemd:
    name: openvpn
    state: started
    enabled: yes
