---
- name: Install all needed packages
  import_tasks: install.yml
  tags: install, openvpn-client
  when: openvpn_scene_install

- name: Configure package
  import_tasks: configure.yml
  tags: config, openvpn-client
  when: openvpn_scene_config
